// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const AUTH_SERVER_ORIGIN = import.meta.env.VITE_AUTH_SERVER_ORIGIN || "https://chekam.onrender.com";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  // Route all requests through our backend proxy to bypass DNS blocking
  fetch: async (url, options) => {
    try {
      // Extract the path after the Supabase URL
      const supabaseUrl = new URL(SUPABASE_URL);
      const requestUrl = new URL(url);
      
      // Check if this is a Supabase request
      if (requestUrl.hostname === supabaseUrl.hostname) {
        const path = requestUrl.pathname + requestUrl.search;
        
        // Route through our proxy
        const proxyUrl = `${AUTH_SERVER_ORIGIN}/api/supabase${path}`;
        
        console.log('[Supabase Proxy] Routing through:', proxyUrl);
        
        const response = await fetch(proxyUrl, {
          ...options,
          headers: {
            ...options?.headers,
            'Authorization': options?.headers?.['Authorization'] || `Bearer ${SUPABASE_PUBLISHABLE_KEY}`,
          },
          credentials: 'include',
        });
        
        return response;
      }
    } catch (error) {
      console.error('[Supabase Proxy] Error:', error);
      // Fall through to regular fetch
    }
    
    // For non-Supabase requests, use default fetch
    return fetch(url, options);
  }
});